// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMGbtUqQRhvaJsSvrIrgKDPYEMh0Rx3Ug',
    appId: '1:892654961434:web:013e935a0e4a33db90e2a3',
    messagingSenderId: '892654961434',
    projectId: 'stoksi-ade-ta',
    authDomain: 'stoksi-ade-ta.firebaseapp.com',
    storageBucket: 'stoksi-ade-ta.firebasestorage.app',
    measurementId: 'G-7Y0QZJY6PK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiUrepq_ZIVO8Ip-gmF8m1RjyyO5xmtQk',
    appId: '1:892654961434:android:09bb6ae2d38925fb90e2a3',
    messagingSenderId: '892654961434',
    projectId: 'stoksi-ade-ta',
    storageBucket: 'stoksi-ade-ta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_yeOaHBM0azYkhb6f-VdwOH0Td9n7zg',
    appId: '1:892654961434:ios:7fa13efd3156ae2090e2a3',
    messagingSenderId: '892654961434',
    projectId: 'stoksi-ade-ta',
    storageBucket: 'stoksi-ade-ta.firebasestorage.app',
    iosBundleId: 'com.example.stoksiTaMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_yeOaHBM0azYkhb6f-VdwOH0Td9n7zg',
    appId: '1:892654961434:ios:7fa13efd3156ae2090e2a3',
    messagingSenderId: '892654961434',
    projectId: 'stoksi-ade-ta',
    storageBucket: 'stoksi-ade-ta.firebasestorage.app',
    iosBundleId: 'com.example.stoksiTaMahasiswa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMGbtUqQRhvaJsSvrIrgKDPYEMh0Rx3Ug',
    appId: '1:892654961434:web:91b91d466178693a90e2a3',
    messagingSenderId: '892654961434',
    projectId: 'stoksi-ade-ta',
    authDomain: 'stoksi-ade-ta.firebaseapp.com',
    storageBucket: 'stoksi-ade-ta.firebasestorage.app',
    measurementId: 'G-3ZMT38XWLX',
  );
}
